# Generated by Django 6.1.2 on 2026-10-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bankcard_expense_job_savingsgoal_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('coins', models.IntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('card_type', models.CharField(choices=[('standard', 'Standard Card'), ('gold', 'CoinCard Gold'), ('vip', 'CoinCard VIP')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_voice',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='note',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='card',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='daily_amount',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='penalty_enabled',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='user',
        ),
        migrations.AddField(
            model_name='bankcard',
            name='title',
            field=models.CharField(default='Card', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
