# Generated by Django 6.1.2 on 2026-10-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_telegramuser_remove_bankcard_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='title',
        ),
        migrations.AddField(
            model_name='bankcard',
            name='balance',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='bank_name',
            field=models.CharField(default='CoinCard Gold', max_length=100),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='card_holder',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Oziq-ovqat', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.CharField(default='Hozir', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.CharField(default='@hr_admin', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Toshkent', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='current_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='card_number',
            field=models.CharField(default='Unknown', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Xarajat', max_length=255),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='coins',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.contactmessage')),
            ],
        ),
    ]
